services:
  moq-js:
    build:
      context: repos/moq-js
      dockerfile: Dockerfile
    command: run dev
    entrypoint: ["npm"]
    ports:
      - "4321:4321"
    profiles:
      - dev
    restart: on-failure
    volumes:
      - ./:/app/
      - /app/node_modules
    working_dir: /app
