#!/bin/bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Must provide exactly one room number -> e.g. './dev/pub 1'"
    exit 1
fi

# Change directory to the root of the project
cd "$(dirname "$0")/.."


if [ ! -d atoms ]; then
	mkdir -p atoms
	
	if [ ! -f dev/bbb.fmp4 ]; then
		if [ ! -f dev/bbb.mp4 ]; then
			echo "Downloading ya boye Big Buck Bunny..."
			wget http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 -O dev/bbb.mp4
		fi

		echo "Converting to a (properly) fragmented MP4..."
		ffmpeg -i dev/bbb.mp4 \
			-c copy \
			-f mp4 -movflags cmaf+separate_moof+delay_moov+skip_trailer+frag_every_frame \
			dev/bbb.fmp4
	fi
	echo -e "\033[31mMP4 atoms do not exist in your system. Please generate them for streaming using moq-pub\nExiting with error.\033[0m" >&2
	exit 1
fi


# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
SCHEME="${SCHEME:-https}"

# Combine the host into a URL.
URL="${URL:-"$SCHEME://$ADDR"}"

# Default to a source video
INPUT="${INPUT:-dev/bbb.fmp4}"

# Print out the watch URL
# echo "Watch URL: https://quic.video/watch/$NAME?server=$ADDR"


cargo run --bin moq-pub -- --name room$1 "$URL"

